# Site settings
title: Orhi the dog
email: orhithedog@gmail.com
description: Orhi the dog coming soon page.
baseurl: "/coming-soon" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site

# Identity
your-name: Orhi the dog
your-title: Follow me on Instagram

# Social settings
500px_url:
facebook_url: 
github_url:
gitlab_url: 
googleplus_url: 
instagram_url: https://instagram.com/orhithedog
linkedin_url:
pinterest_url:
slack_url:
twitter_url:

# Build settings
markdown: kramdown
